### ISSUE TITLE
Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by joecorkerton** [opvasger/elm-minify#16]
elm-minify/src/api.js:48
`return text.substring(text.length - search.length) === search`

I imagine this is a similar issue to #15 ?

**Comment by opvasger** [comment]
yes, it's related 👍

Apparantly the `resource` property on modules isn't always there during webpack compilation. This is a problem as I need to consistently figure out if a module is read from an `.elm` file. I suppose i could check if the file was loaded with the `elm-webpack-loader` instead.

I'm not sure if the module with the missing `resource` property can ever have loaded elm code - if so, I could just check if it's there and ignore the module otherwise...

**Comment by opvasger** [comment]
as of 1.5.3, I've changed the conditions for minification, which should resolve your issue. Let me know if it works out 👍

**Comment by joecorkerton** [comment]
Just tested it out, working great! Saved us 20kb 👍
